### ISSUE TITLE
[BUG] śmierć projektu

### ISSUE THREAD

**Issue by Jacob1Tm** [xKubsoneQ/milionerzy-js#7]
**Opis błędu**
Śmierć projektu

**Co spowodowało błąd?**
nie wiem.

**Screeny**
https://p.jacobtm.ga/i/mpkqa.png

**Inne informacje**
fajny projekt był

**Comment by xKubsoneQ** [comment]
brak checi i czasu

**Comment by Jacob1Tm** [comment]
> brak checi i czasu

jak to tak :<<<<
